spring.application.name=discord-muppet
playwright.skip.browser.download=1

discord.credentials.email=test@email.com
discord.credentials.password=password

debug.screenshot=true

user.agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
spring.profiles.active=dev